"""Initial schema

Revision ID: 096c68f18db7
Revises: 
Create Date: 2026-10-02 18:23:56.528692
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '096c68f18db7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('auth_subject', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('sex', sa.Enum('M', 'F', name='sex'), nullable=True),
    sa.Column('position', sa.String(length=80), nullable=True),
    sa.Column('owns_net', sa.Boolean(), nullable=False),
    sa.Column('profile_visibility', sa.String(length=16), nullable=False),
    sa.Column('game_updates', sa.Boolean(), nullable=False),
    sa.Column('game_reminders', sa.Boolean(), nullable=False),
    sa.Column('friend_requests', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_auth_subject'), 'users', ['auth_subject'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('location_name', sa.String(length=160), nullable=True),
    sa.Column('address', sa.String(length=240), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip', sa.String(length=10), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('setting', sa.Enum('sand', 'grass', 'indoor', name='setting'), nullable=False),
    sa.Column('nets_available', sa.Integer(), nullable=False),
    sa.Column('nets_needed', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.Enum('public', 'private', name='visibility'), nullable=False),
    sa.Column('allow_add_courts', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', name='eventstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('nets_available >= 0'),
    sa.CheckConstraint('nets_needed >= 0'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_date_time'), 'events', ['date_time'], unique=False)
    op.create_index(op.f('ix_events_owner_id'), 'events', ['owner_id'], unique=False)
    op.create_table('friendships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_low_id', sa.Uuid(), nullable=False),
    sa.Column('user_high_id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('user_low_id <> user_high_id'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_high_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_low_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_low_id', 'user_high_id', name='uq_friend_pair')
    )
    op.create_table('groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_owner_id'), 'groups', ['owner_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('related_resource_type', sa.String(length=32), nullable=True),
    sa.Column('related_resource_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_recipient_created', 'notifications', ['recipient_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_table('push_devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_push_device_user_device')
    )
    op.create_index(op.f('ix_push_devices_user_id'), 'push_devices', ['user_id'], unique=False)
    op.create_table('courts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('RCO', 'Co-ed', "Men's", "Women's", name='courtcategory'), nullable=False),
    sa.Column('type', sa.Enum('Doubles', 'Fours', 'Sixes', name='courtformat'), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_players > 0'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courts_event_id'), 'courts', ['event_id'], unique=False)
    op.create_table('event_groups',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'group_id')
    )
    op.create_table('group_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_member')
    )
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_members_user_id'), 'group_members', ['user_id'], unique=False)
    op.create_table('push_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.String(length=80), nullable=True),
    sa.Column('ticket_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['push_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', 'device_id', name='uq_push_delivery_notification_device')
    )
    op.create_index(op.f('ix_push_deliveries_device_id'), 'push_deliveries', ['device_id'], unique=False)
    op.create_index(op.f('ix_push_deliveries_notification_id'), 'push_deliveries', ['notification_id'], unique=False)
    op.create_index('ix_push_delivery_pending', 'push_deliveries', ['status', 'next_attempt_at'], unique=False)
    op.create_table('court_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('court_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_id', 'user_id', name='uq_membership_court_user'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_membership_event_user')
    )
    op.create_index(op.f('ix_court_memberships_court_id'), 'court_memberships', ['court_id'], unique=False)
    op.create_index(op.f('ix_court_memberships_event_id'), 'court_memberships', ['event_id'], unique=False)
    op.create_index(op.f('ix_court_memberships_user_id'), 'court_memberships', ['user_id'], unique=False)
    op.create_table('court_waitlist_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('court_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_waitlist_event_user')
    )
    op.create_index(op.f('ix_court_waitlist_entries_court_id'), 'court_waitlist_entries', ['court_id'], unique=False)
    op.create_index(op.f('ix_court_waitlist_entries_event_id'), 'court_waitlist_entries', ['event_id'], unique=False)
    op.create_index(op.f('ix_court_waitlist_entries_user_id'), 'court_waitlist_entries', ['user_id'], unique=False)
    op.create_index('ix_waitlist_court_created_id', 'court_waitlist_entries', ['court_id', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waitlist_court_created_id', table_name='court_waitlist_entries')
    op.drop_index(op.f('ix_court_waitlist_entries_user_id'), table_name='court_waitlist_entries')
    op.drop_index(op.f('ix_court_waitlist_entries_event_id'), table_name='court_waitlist_entries')
    op.drop_index(op.f('ix_court_waitlist_entries_court_id'), table_name='court_waitlist_entries')
    op.drop_table('court_waitlist_entries')
    op.drop_index(op.f('ix_court_memberships_user_id'), table_name='court_memberships')
    op.drop_index(op.f('ix_court_memberships_event_id'), table_name='court_memberships')
    op.drop_index(op.f('ix_court_memberships_court_id'), table_name='court_memberships')
    op.drop_table('court_memberships')
    op.drop_index('ix_push_delivery_pending', table_name='push_deliveries')
    op.drop_index(op.f('ix_push_deliveries_notification_id'), table_name='push_deliveries')
    op.drop_index(op.f('ix_push_deliveries_device_id'), table_name='push_deliveries')
    op.drop_table('push_deliveries')
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    op.drop_table('group_members')
    op.drop_table('event_groups')
    op.drop_index(op.f('ix_courts_event_id'), table_name='courts')
    op.drop_table('courts')
    op.drop_index(op.f('ix_push_devices_user_id'), table_name='push_devices')
    op.drop_table('push_devices')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index('ix_notifications_recipient_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_groups_owner_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_events_owner_id'), table_name='events')
    op.drop_index(op.f('ix_events_date_time'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_auth_subject'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
